name: Run Wallets Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
          - https://test-app.deriv.com
      suite:
        type: choice
        description: Run smoke or full test suite
        options:
          - full
          - wip/Wallets/cashier
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      # matrix:
      #  containers: [1,2]

    steps:
      - name: Checkout external repository with Cypress tests
        uses: actions/checkout@v4
        with:
          repository: deriv-com/e2e-deriv-app # Replace with your repository name

      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          # start: npm start
          # wait-on: 'http://localhost:3000' # Waits for above
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: false # Runs test in parallel using settings above
          spec: cypress/e2e/${{ env.TEST_SUITE }}/*.js
          # group: 'e2e Tests'

        env:
          TEST_SUITE: ${{ github.event.inputs.suite }}
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set Base Url from client_payload.
          CYPRESS_BASE_URL: '${{ github.event.inputs.environment }}'
          # Send PR details to Cypress test run
          COMMIT_INFO_MESSAGE: Manual Run of "${{ github.event.inputs.suite }} tests" on "${{ github.event.inputs.environment }}"
          # Set test env variables
          E2E_DERIV_LOGIN: ${{ secrets.E2E_WALLETS_LOGIN }}
          E2E_DERIV_PASSWORD: ${{ secrets.E2E_WALLETS_PASSWORD }}
          E2E_CONFIG_APPID: ${{ secrets.E2E_WALLETS_CONFIG_APPID }}
          E2E_CONFIG_SERVER: ${{ secrets.E2E_WALLETS_CONFIG_SERVER }}
          E2E_OAUTH_URL: ${{ secrets.E2E_OAUTH_URL }}
          E2E_MT5_LOGIN: ${{ secrets.E2E_MT5_LOGIN }}
          E2E_MT5_PASSWORD: ${{ secrets.E2E_MT5_PASSWORD }}
          E2E_MT5_BASEURL: ${{ secrets.E2E_MT5_BASEURL }}
          E2E_STD_CONFIG_SERVER: ${{ secrets.E2E_WALLETS_CONFIG_SERVER }}
          E2E_STD_CONFIG_APPID: ${{ secrets.E2E_WALLETS_CONFIG_APPID }}
          E2E_DOUGHFLOW_CONFIG_SERVER: ${{ secrets.E2E_DOUGHFLOW_CONFIG_SERVER }}
          E2E_DOUGHFLOW_CONFIG_APPID: ${{ secrets.E2E_DOUGHFLOW_CONFIG_APPID }}
          E2E_QABOX_URL: ${{ secrets.E2E_QABOX_URL }}
          E2E_MAIN_QABOX_URL: ${{ secrets.E2E_MAIN_QABOX_URL }}
          E2E_QABOX_LOGIN: ${{ secrets.E2E_QABOX_LOGIN }}
          E2E_QABOX_PASSWORD: ${{ secrets.E2E_QABOX_PASSWORD }}
