name: 'Check formatting'
on:
    pull_request:
        branches: master
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
    prettier:
        name: Prettier
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            repository: deriv-com/e2e-deriv-app
        - name: Get changed files
          uses: tj-actions/changed-files@v43
        - name: List changed files
          env:
            ALL_CHANGED_FILES: ${{steps.changed-files.outputs.all_changed_files}}
          run: | 
            echo CHANGES = $ALL_CHANGED_FILES >> $GITHUB_ENV
        - uses: actions/setup-node@v4
          with: 
            node-version: latest
        - name: Install Depdendencies
          run: npm i -D
        - name: Check formatting
          run: npx prettier --check "${{steps.changed-files.outputs.all_changed_files}}"


    