name: 'Check formatting'
on:
    pull_request:
        branches: master
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
    prettier:
        name: Prettier
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            repository: deriv-com/e2e-deriv-app
            ref: ${{ github.head_ref }}
            fetch-depth: 0
        # - name: Get changed files
        #   uses: tj-actions/changed-files@v43
        #   with:
        #         since_last_remote_commit: true 
        # - name: List changed files
        #   env:
        #     ALL_CHANGED_FILES: ${{steps.changed-files.outputs.all_changed_files}}
        #   run: | 
        #     echo CHANGES = $ALL_CHANGED_FILES >> $GITHUB_ENV
        #     for file in ${ALL_CHANGED_FILES}; do
        #       echo "$file was changed"
        #     done
        # - uses: actions/setup-node@v4
        #   with: 
        #     node-version: latest
        # - name: Install Depdendencies
        #   run: npm i -D
        # - name: Check formatting
        #   run: npx prettier --check $(git diff --name-only --diff-filter d | grep '.js$' | xargs)
        - name: Prettify code
          uses: creyD/prettier_action@v4.3
          with:
          # This part is also where you can pass other options, for example:
            prettier_options: --check
            only_changed: True


    